In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import Lasso, LassoCV
from sklearn.linear_model import Ridge,RidgeCV
from sklearn.linear_model import ElasticNet, ElasticNetCV
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [3]:
sales_df=pd.read_csv('Advertising.csv')
sales_df.head()

TV  Radio  Newspaper  Sales  Unnamed: 4      TV^2 tv.radio   tv.news  \
0  230.1   37.8       69.2   22.1         NaN   52,946    8,698    15,923    
1   44.5   39.3       45.1   10.4         NaN       NaN      NaN       NaN   
2   17.2   45.9       69.3    9.3         NaN       NaN      NaN       NaN   
3  151.5   41.3       58.5   18.5         NaN       NaN      NaN       NaN   
4  180.8   10.8       58.4   12.9         NaN       NaN      NaN       NaN   

   radio^2 radio.news   news^2  
0   1,429      2,616    4,789   
1      NaN        NaN      NaN  
2      NaN        NaN      NaN  
3      NaN        NaN      NaN  
4      NaN        NaN      NaN

# Defining the X and y 

In [5]:
X=sales_df[['TV','Radio','Newspaper']]
y=sales_df['Sales']

In [6]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.7,random_state=101)

In [8]:
len(x_test)

140

In [9]:
model=LinearRegression()

In [10]:
model.fit(x_train,y_train)

LinearRegression()

In [11]:
model.intercept_

3.688865176160432

In [12]:
model.coef_

array([ 0.04520678,  0.17337884, -0.01275654])

In [13]:
list((zip(x_train.columns,model.coef_)))

[('TV', 0.045206780237092854),
 ('Radio', 0.17337883852384028),
 ('Newspaper', -0.012756544989635828)]

Sales=2.708+0.044TV+0.199Radio+0.006*Newspaper

# predicting the Y value for the test set

In [15]:
y_pred=model.predict(x_test)

In [17]:
#Creating a dataframe with three column name : actual, Predicted, and Residuals
#to store the respective value
test_pred_df=pd.DataFrame({'actual':y_test,'predicted': np.round(y_pred,2)})

In [18]:
test_pred_df[:10]

actual  predicted
37     14.7      15.05
109    19.8      19.83
31     11.9      11.32
89     16.7      16.28
66      9.5       9.35
119     6.6       7.06
54     20.2      20.36
74     17.0      17.43
145    10.3      10.25
142    20.1      18.93

In [19]:
# y_train Contains the actual value and the predicted value is 
#returned the predict() after passing the X values of the training Data
r2=metrics.r2_score(y_train,model.predict(x_train))
print('r2 score :',r2)

r2 score : 0.8921437486086257


In [20]:
r2=metrics.r2_score(y_test,model.predict(x_test))
print('r2 Score: ',r2)

r2 Score:  0.8903806044566008


In [22]:
#y_pred contains value of test Data
mse= metrics.mean_squared_error(y_test,y_pred)
mse

3.133045590522073

In [23]:
rmse=round(np.sqrt(mse),2)
print("Rmse :",rmse)

Rmse : 1.77


In [24]:
df=pd.read_csv("Advertising.csv")
df.head()

TV  Radio  Newspaper  Sales  Unnamed: 4      TV^2 tv.radio   tv.news  \
0  230.1   37.8       69.2   22.1         NaN   52,946    8,698    15,923    
1   44.5   39.3       45.1   10.4         NaN       NaN      NaN       NaN   
2   17.2   45.9       69.3    9.3         NaN       NaN      NaN       NaN   
3  151.5   41.3       58.5   18.5         NaN       NaN      NaN       NaN   
4  180.8   10.8       58.4   12.9         NaN       NaN      NaN       NaN   

   radio^2 radio.news   news^2  
0   1,429      2,616    4,789   
1      NaN        NaN      NaN  
2      NaN        NaN      NaN  
3      NaN        NaN      NaN  
4      NaN        NaN      NaN

In [25]:
x_train,x_other,y_train,y_other=train_test_split(df[['TV','Radio','Newspaper']],df['Sales'],test_size=0.7,random_state=42)

In [26]:
x_eval,x_test,y_eval,y_test=train_test_split(x_other,y_other,test_size=0.5,random_state=42)

In [28]:
from sklearn.preprocessing import StandardScaler
#(actual value-mean)/standard deviation (aka Z-Score)
# mean=0
#std=1

In [29]:
scaler=StandardScaler()

In [31]:
x_train = scaler.fit_transform(x_train)

In [32]:
x_test=scaler.transform(x_test)

In [33]:
x_eval= scaler.transform(x_eval)

In [34]:
lm=LinearRegression()

In [35]:
lm.fit(x_train,y_train)

LinearRegression()

In [36]:
pred=lm.predict(x_eval)

In [38]:
metrics.mean_squared_error(y_eval,pred)

2.735520454736166

Now evaluate and perform the usual operation finally use the test data only once

# K fold Validation

In [40]:
sales_df=pd.read_csv('Advertising.csv')
sales_df.head()

TV  Radio  Newspaper  Sales  Unnamed: 4      TV^2 tv.radio   tv.news  \
0  230.1   37.8       69.2   22.1         NaN   52,946    8,698    15,923    
1   44.5   39.3       45.1   10.4         NaN       NaN      NaN       NaN   
2   17.2   45.9       69.3    9.3         NaN       NaN      NaN       NaN   
3  151.5   41.3       58.5   18.5         NaN       NaN      NaN       NaN   
4  180.8   10.8       58.4   12.9         NaN       NaN      NaN       NaN   

   radio^2 radio.news   news^2  
0   1,429      2,616    4,789   
1      NaN        NaN      NaN  
2      NaN        NaN      NaN  
3      NaN        NaN      NaN  
4      NaN        NaN      NaN

In [41]:
X=sales_df[['TV','Radio','Newspaper']]
y=sales_df['Sales']

In [42]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=101)

In [43]:
lm=LinearRegression()

In [44]:
scaler=StandardScaler()

In [46]:
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [47]:
from sklearn.model_selection import cross_val_score

In [48]:
scores=cross_val_score(lm,x_train,y_train,scoring='r2',cv=5)

In [49]:
#r2=.75, .85
#mse= -2.5,-3.5

In [50]:
from sklearn.metrics import SCORERS

In [51]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [52]:
#  https://scikit-learn.org/stable/modules/model_evaluation.html

In [53]:
abs(scores.mean())

0.8254757566265983

In [54]:
scores

array([0.91780509, 0.81092063, 0.89856072, 0.61359053, 0.88650181])

In [55]:
lm.fit(x_train,y_train)

LinearRegression()

In [56]:
lm.coef_

array([ 3.9656481 ,  2.42561987, -0.26342377])

In [57]:
pred=lm.predict(x_test)

In [58]:
metrics.r2_score(y_test,pred)

0.8682681363267276